matrix:
  include:
    # For the md files to pdf conversion
    - language: c
      # stuff that is supposed to be done iwth node.js
      before_install:
        - wget https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-1-amd64.deb
        - ar p pandoc-1.19.2.1-1-amd64.deb data.tar.gz | tar zx ./usr/bin/pandoc --strip-components 3
      addons:
        apt:
          packages:
            texlive
            lmodern
      script:
        PANDOC=./pandoc make all
      deploy:
        provider: releases
        api_key:
          secure: $GH_TOKEN
        file_glob: true
        file: out/*
        skip_cleanup: true
        on:
          tags: true
    
    # IONIC stuff
    - language: node:js
      node_js:
        - "8.10.0"
      before_script:
        - npm install -g ionic cordova
        #- cd testProject # Should be updated to the correct path when we have set up the real project
        - rm -rf node_modules # Added to correct some dependency errors
        - npm i # Added to correct some dependency errors
      script:
        - ionic cordova build browser - prod
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local_dir: www




notifications:
  travis encrypt "eda397group4:qJDEgEHMpRJtgrJ5pNYZBEFp" --add notifications.slack
